function f(p) {
  return Object.assign({
    brightness: 1, contrast: 1, saturate: 1, hue: 0, sepia: 0, grayscale: 0,
    vignette: 0, fade: 0, grain: 0, temperature: 0, tier: "free",
  }, p);
}

const FILTERS = [
  f({ id: "original", name: "Original", category: "Natural" }),
  f({ id: "open-sky", name: "Open Sky", category: "Natural", brightness: 1.08, contrast: 1.06, saturate: 1.14, temperature: -0.18, overlay: { color: "#7EB6FF", mix: "soft-light", amount: 0.28 } }),
  f({ id: "true-color", name: "True Color", category: "Natural", contrast: 1.08, saturate: 1.06 }),
  f({ id: "garden-fresh", name: "Garden Fresh", category: "Natural", brightness: 1.04, saturate: 1.28, hue: -8, overlay: { color: "#4CAF50", mix: "soft-light", amount: 0.22 } }),
  f({ id: "soft-daylight", name: "Soft Daylight", category: "Natural", brightness: 1.1, contrast: 0.88, saturate: 0.92, fade: 0.12 }),
  f({ id: "clear-air", name: "Clear Air", category: "Natural", brightness: 1.06, contrast: 1.14, saturate: 1.08, temperature: -0.08 }),
  f({ id: "meadow", name: "Meadow", category: "Natural", saturate: 1.22, hue: 12, overlay: { color: "#C6E27A", mix: "soft-light", amount: 0.3 } }),
  f({ id: "golden-hour", name: "Golden Hour", category: "Natural", brightness: 1.04, contrast: 1.08, saturate: 1.12, sepia: 0.18, temperature: 0.45, overlay: { color: "#FFB347", mix: "overlay", amount: 0.28 } }),
  f({ id: "cool-shade", name: "Cool Shade", category: "Natural", brightness: 0.96, contrast: 1.05, saturate: 0.9, temperature: -0.35, overlay: { color: "#6A8CFF", mix: "soft-light", amount: 0.3 } }),
  f({ id: "morning-dew", name: "Morning Dew", category: "Natural", brightness: 1.14, contrast: 0.92, saturate: 0.95, temperature: -0.12, fade: 0.1 }),
  f({ id: "balanced", name: "Balanced", category: "Natural", contrast: 1.1, saturate: 1.04, brightness: 1.02 }),
  f({ id: "horizon", name: "Horizon", category: "Natural", contrast: 0.94, saturate: 0.96, fade: 0.16, temperature: 0.08 }),
  f({ id: "prairie", name: "Prairie", category: "Natural", saturate: 1.1, temperature: 0.28, overlay: { color: "#D4A017", mix: "soft-light", amount: 0.22 } }),
  f({ id: "skyline", name: "Skyline", category: "Natural", contrast: 1.12, saturate: 1.08, overlay: { color: "#87CEEB", mix: "soft-light", amount: 0.2 } }),
  f({ id: "soft-glow", name: "Soft Glow", category: "Portrait", tier: "studio", brightness: 1.1, contrast: 0.86, saturate: 0.94, fade: 0.14, overlay: { color: "#FFE0C2", mix: "soft-light", amount: 0.28 } }),
  f({ id: "peach-skin", name: "Peach Skin", category: "Portrait", tier: "studio", brightness: 1.06, saturate: 1.08, overlay: { color: "#FFC0A8", mix: "soft-light", amount: 0.38 } }),
  f({ id: "fair-tone", name: "Fair Tone", category: "Portrait", tier: "studio", brightness: 1.12, contrast: 0.9, saturate: 0.86, fade: 0.1 }),
  f({ id: "warm-face", name: "Warm Face", category: "Portrait", tier: "studio", brightness: 1.04, saturate: 1.1, temperature: 0.32, overlay: { color: "#FFB088", mix: "overlay", amount: 0.22 } }),
  f({ id: "studio-soft", name: "Studio Soft", category: "Portrait", tier: "studio", brightness: 1.08, contrast: 0.84, saturate: 0.9, fade: 0.08 }),
  f({ id: "candle", name: "Candle", category: "Portrait", tier: "studio", brightness: 0.92, contrast: 1.12, saturate: 1.15, temperature: 0.55, overlay: { color: "#FF7A2E", mix: "soft-light", amount: 0.35 }, vignette: 0.35 }),
  f({ id: "rose-milk", name: "Rose Milk", category: "Portrait", tier: "studio", brightness: 1.08, contrast: 0.9, overlay: { color: "#F4B6C2", mix: "soft-light", amount: 0.4 } }),
  f({ id: "ivory", name: "Ivory", category: "Portrait", tier: "studio", brightness: 1.1, contrast: 0.88, saturate: 0.82, sepia: 0.12, fade: 0.16 }),
  f({ id: "velvet", name: "Velvet", category: "Portrait", tier: "studio", brightness: 0.96, contrast: 1.2, saturate: 1.08, temperature: 0.18, vignette: 0.28 }),
  f({ id: "porcelain", name: "Porcelain", category: "Portrait", tier: "studio", brightness: 1.16, contrast: 0.82, saturate: 0.72, fade: 0.18 }),
  f({ id: "blush", name: "Blush", category: "Portrait", tier: "studio", saturate: 1.05, overlay: { color: "#E86A92", mix: "soft-light", amount: 0.32 } }),
  f({ id: "amber-skin", name: "Amber Skin", category: "Portrait", tier: "studio", contrast: 1.06, temperature: 0.4, overlay: { color: "#E09A4A", mix: "overlay", amount: 0.28 } }),
  f({ id: "teal-orange", name: "Teal Orange", category: "Cinematic", tier: "studio", contrast: 1.18, saturate: 1.12, overlay: { color: "#2A6F7A", mix: "soft-light", amount: 0.35 }, vignette: 0.22 }),
  f({ id: "noir", name: "Noir", category: "Cinematic", tier: "studio", brightness: 0.92, contrast: 1.35, grayscale: 1, vignette: 0.42 }),
  f({ id: "blockbuster", name: "Blockbuster", category: "Cinematic", tier: "studio", contrast: 1.28, saturate: 1.2, brightness: 0.97, vignette: 0.2 }),
  f({ id: "dune", name: "Dune", category: "Cinematic", tier: "studio", brightness: 1.04, contrast: 1.1, saturate: 0.78, sepia: 0.22, overlay: { color: "#C4A574", mix: "overlay", amount: 0.32 }, fade: 0.08 }),
  f({ id: "night-ride", name: "Night Ride", category: "Cinematic", tier: "studio", brightness: 0.82, contrast: 1.22, saturate: 0.85, overlay: { color: "#1B3C6E", mix: "soft-light", amount: 0.45 }, vignette: 0.4 }),
  f({ id: "steel", name: "Steel", category: "Cinematic", tier: "studio", contrast: 1.16, saturate: 0.55, overlay: { color: "#6B7C8F", mix: "color", amount: 0.35 } }),
  f({ id: "ember", name: "Ember", category: "Cinematic", tier: "studio", brightness: 0.9, contrast: 1.2, saturate: 1.15, overlay: { color: "#C43C12", mix: "soft-light", amount: 0.4 }, vignette: 0.32 }),
  f({ id: "fog-city", name: "Fog City", category: "Cinematic", tier: "studio", brightness: 1.08, contrast: 0.78, saturate: 0.62, fade: 0.28, overlay: { color: "#9BB0C4", mix: "soft-light", amount: 0.32 } }),
  f({ id: "rain", name: "Rain", category: "Cinematic", tier: "studio", contrast: 1.14, saturate: 0.7, temperature: -0.28, overlay: { color: "#4A6A80", mix: "soft-light", amount: 0.3 } }),
  f({ id: "epic", name: "Epic", category: "Cinematic", tier: "studio", contrast: 1.3, saturate: 1.08, brightness: 0.95, vignette: 0.36 }),
  f({ id: "anamorphic", name: "Anamorphic", category: "Cinematic", tier: "studio", contrast: 1.12, saturate: 0.92, fade: 0.1, vignette: 0.5 }),
  f({ id: "director", name: "Director", category: "Cinematic", tier: "studio", contrast: 1.18, saturate: 0.95, temperature: 0.12, vignette: 0.18, fade: 0.06 }),
  f({ id: "portra-400", name: "Portra 400", category: "Film", tier: "studio", contrast: 0.94, saturate: 1.08, brightness: 1.04, overlay: { color: "#F0D2B0", mix: "soft-light", amount: 0.28 }, fade: 0.1, grain: 0.18 }),
  f({ id: "superia", name: "Superia", category: "Film", tier: "studio", saturate: 1.22, contrast: 1.06, grain: 0.16 }),
  f({ id: "cinestill", name: "Cinestill", category: "Film", tier: "studio", contrast: 1.12, saturate: 1.1, overlay: { color: "#1A2A48", mix: "soft-light", amount: 0.28 }, grain: 0.14 }),
  f({ id: "expired", name: "Expired", category: "Film", tier: "studio", contrast: 0.88, saturate: 0.75, hue: 18, sepia: 0.15, fade: 0.22, grain: 0.32 }),
  f({ id: "super-8", name: "Super 8", category: "Film", tier: "studio", contrast: 1.15, saturate: 1.25, sepia: 0.2, vignette: 0.38, grain: 0.4 }),
  f({ id: "polaroid", name: "Polaroid", category: "Film", tier: "studio", brightness: 1.08, contrast: 0.86, saturate: 0.88, fade: 0.2, overlay: { color: "#F2E4C8", mix: "soft-light", amount: 0.35 } }),
  f({ id: "cross-process", name: "Cross Process", category: "Film", tier: "studio", contrast: 1.22, saturate: 1.35, hue: -18 }),
  f({ id: "slide", name: "Slide", category: "Film", tier: "studio", contrast: 1.24, saturate: 1.3, brightness: 1.04 }),
  f({ id: "chrome", name: "Chrome", category: "Film", tier: "studio", contrast: 1.2, saturate: 1.18 }),
  f({ id: "halation", name: "Halation", category: "Film", tier: "studio", contrast: 1.08, brightness: 1.04, fade: 0.08 }),
  f({ id: "sixteen-mm", name: "Sixteen MM", category: "Film", tier: "studio", contrast: 1.1, saturate: 0.92, vignette: 0.3, grain: 0.36, sepia: 0.08 }),
  f({ id: "gold-200", name: "Gold 200", category: "Film", tier: "studio", saturate: 1.16, temperature: 0.38, overlay: { color: "#E8B84A", mix: "soft-light", amount: 0.32 }, grain: 0.14 }),
  f({ id: "ultramax", name: "Ultramax", category: "Film", tier: "studio", contrast: 1.14, saturate: 1.2, grain: 0.2 }),
  f({ id: "ektar", name: "Ektar", category: "Film", tier: "studio", contrast: 1.16, saturate: 1.38, brightness: 1.02 }),
  f({ id: "agfa-vista", name: "Agfa Vista", category: "Film", tier: "studio", saturate: 1.12, grain: 0.16 }),
  f({ id: "lomo", name: "Lomo", category: "Film", tier: "studio", contrast: 1.22, saturate: 1.4, hue: 8, vignette: 0.55 }),
  f({ id: "ink-contrast", name: "Ink Contrast", category: "Mono", contrast: 1.42, grayscale: 1, brightness: 0.98, vignette: 0.12 }),
  f({ id: "silver-grain", name: "Silver Grain", category: "Mono", contrast: 1.12, grayscale: 1, grain: 0.45, fade: 0.08 }),
  f({ id: "ash-soft", name: "Ash Soft", category: "Mono", brightness: 1.08, contrast: 0.84, grayscale: 1, fade: 0.18 }),
  f({ id: "charcoal", name: "Charcoal", category: "Mono", brightness: 0.88, contrast: 1.28, grayscale: 1, vignette: 0.3 }),
  f({ id: "newspaper", name: "Newspaper", category: "Mono", contrast: 1.35, grayscale: 1, brightness: 1.06, grain: 0.28 }),
  f({ id: "high-key", name: "High Key", category: "Mono", brightness: 1.28, contrast: 0.78, grayscale: 1, fade: 0.22 }),
  f({ id: "low-key", name: "Low Key", category: "Mono", brightness: 0.72, contrast: 1.32, grayscale: 1, vignette: 0.48 }),
  f({ id: "paper", name: "Paper", category: "Mono", brightness: 1.12, contrast: 0.9, grayscale: 1, overlay: { color: "#EDE4D4", mix: "soft-light", amount: 0.4 } }),
  f({ id: "selenium", name: "Selenium", category: "Mono", contrast: 1.14, grayscale: 1, overlay: { color: "#6A7B8A", mix: "color", amount: 0.35 } }),
  f({ id: "platinum", name: "Platinum", category: "Mono", contrast: 1.08, grayscale: 1, overlay: { color: "#C5B89A", mix: "color", amount: 0.32 }, fade: 0.1 }),
  f({ id: "amber", name: "Amber", category: "Color", tier: "studio", saturate: 1.1, overlay: { color: "#E09020", mix: "color", amount: 0.42 } }),
  f({ id: "grape", name: "Grape", category: "Color", tier: "studio", saturate: 1.05, hue: -24, overlay: { color: "#7B4BB7", mix: "color", amount: 0.48 } }),
  f({ id: "citrus", name: "Citrus", category: "Color", tier: "studio", saturate: 1.2, overlay: { color: "#D6E04A", mix: "color", amount: 0.4 } }),
  f({ id: "coral", name: "Coral", category: "Color", tier: "studio", saturate: 1.12, overlay: { color: "#E86A7A", mix: "color", amount: 0.42 } }),
  f({ id: "mint", name: "Mint", category: "Color", tier: "studio", overlay: { color: "#3ECF9A", mix: "color", amount: 0.4 } }),
  f({ id: "azure", name: "Azure", category: "Color", tier: "studio", overlay: { color: "#2A7AE0", mix: "color", amount: 0.42 } }),
  f({ id: "honey", name: "Honey", category: "Color", tier: "studio", temperature: 0.3, overlay: { color: "#D4A017", mix: "color", amount: 0.38 } }),
  f({ id: "ice", name: "Ice", category: "Color", tier: "studio", brightness: 1.08, saturate: 0.85, overlay: { color: "#A8D4E8", mix: "color", amount: 0.4 }, fade: 0.1 }),
  f({ id: "sunset", name: "Sunset", category: "Color", tier: "studio", contrast: 1.1, overlay: { color: "#FF6A3A", mix: "overlay", amount: 0.35 } }),
  f({ id: "lime", name: "Lime", category: "Color", tier: "studio", saturate: 1.18, overlay: { color: "#7ED321", mix: "color", amount: 0.4 } }),
  f({ id: "cobalt", name: "Cobalt", category: "Color", tier: "studio", contrast: 1.12, overlay: { color: "#1A4A9A", mix: "color", amount: 0.45 } }),
  f({ id: "magenta-wash", name: "Magenta Wash", category: "Color", tier: "studio", overlay: { color: "#C0368A", mix: "color", amount: 0.42 } }),
  f({ id: "vintage-01", name: "Vintage-01", category: "Vintage", tier: "studio", contrast: 1.16, saturate: 0.78, sepia: 0.28, fade: 0.16, overlay: { color: "#E8D5A3", mix: "overlay", amount: 0.32 }, vignette: 0.22 }),
  f({ id: "vintage-02", name: "Vintage-02", category: "Vintage", tier: "studio", contrast: 1.08, saturate: 0.7, sepia: 0.35, brightness: 1.04, fade: 0.12 }),
  f({ id: "vintage-03", name: "Vintage-03", category: "Vintage", tier: "studio", contrast: 1.2, saturate: 0.62, brightness: 0.96, vignette: 0.34, grain: 0.22 }),
  f({ id: "memo", name: "Memo", category: "Vintage", contrast: 0.92, saturate: 0.55, fade: 0.22, overlay: { color: "#B0B8C0", mix: "soft-light", amount: 0.28 } }),
  f({ id: "retro-fade", name: "Retro Fade", category: "Vintage", tier: "studio", contrast: 0.82, saturate: 0.72, fade: 0.32, sepia: 0.12 }),
  f({ id: "sepia-road", name: "Sepia Road", category: "Vintage", tier: "studio", sepia: 0.7, contrast: 1.1, brightness: 1.02, vignette: 0.18 }),
  f({ id: "dusty", name: "Dusty", category: "Vintage", tier: "studio", saturate: 0.68, contrast: 0.94, overlay: { color: "#C4B49A", mix: "overlay", amount: 0.38 }, grain: 0.24, fade: 0.14 }),
  f({ id: "faded-poly", name: "Faded Poly", category: "Vintage", tier: "studio", brightness: 1.1, contrast: 0.8, saturate: 0.74, fade: 0.26 }),
  f({ id: "seventies", name: "Seventies", category: "Vintage", tier: "studio", saturate: 0.85, hue: 12, vignette: 0.2 }),
  f({ id: "nineties", name: "Nineties", category: "Vintage", tier: "studio", contrast: 1.08, saturate: 0.8, fade: 0.12 }),
  f({ id: "vhs-soft", name: "VHS Soft", category: "Vintage", tier: "studio", contrast: 0.9, saturate: 1.15, grain: 0.3, fade: 0.1 }),
  f({ id: "postcard", name: "Postcard", category: "Vintage", tier: "studio", contrast: 1.14, saturate: 1.18, sepia: 0.14 }),
  f({ id: "bright", name: "Bright", category: "Mood", brightness: 1.22, contrast: 1.04, saturate: 1.08 }),
  f({ id: "story", name: "Story", category: "Mood", contrast: 1.12, saturate: 0.92, fade: 0.1, vignette: 0.16 }),
  f({ id: "natural-mood", name: "Natural", category: "Mood", contrast: 1.08, saturate: 1.1, brightness: 1.03, temperature: 0.08 }),
  f({ id: "warm", name: "Warm", category: "Mood", saturate: 1.08, temperature: 0.48, overlay: { color: "#FF9A4A", mix: "soft-light", amount: 0.32 } }),
  f({ id: "dark", name: "Dark", category: "Mood", brightness: 0.78, contrast: 1.18, saturate: 0.72, grayscale: 0.15, vignette: 0.28 }),
  f({ id: "moody", name: "Moody", category: "Mood", brightness: 0.88, contrast: 1.2, saturate: 0.8, vignette: 0.36 }),
  f({ id: "dream", name: "Dream", category: "Mood", brightness: 1.12, contrast: 0.8, saturate: 0.88, fade: 0.2 }),
  f({ id: "haze", name: "Haze", category: "Mood", brightness: 1.1, contrast: 0.74, saturate: 0.7, fade: 0.3 }),
  f({ id: "bleach", name: "Bleach", category: "Mood", brightness: 1.16, contrast: 1.22, saturate: 0.45, fade: 0.08 }),
  f({ id: "crush", name: "Crush", category: "Mood", brightness: 0.94, contrast: 1.38, saturate: 1.15, vignette: 0.2 }),
  f({ id: "glow-up", name: "Glow Up", category: "Mood", brightness: 1.18, contrast: 0.92, saturate: 1.16 }),
  f({ id: "nightfall", name: "Nightfall", category: "Mood", brightness: 0.7, contrast: 1.16, saturate: 0.85, vignette: 0.44 }),
];

const CATEGORIES = ["All", "Natural", "Portrait", "Cinematic", "Film", "Mono", "Color", "Vintage", "Mood"];
if (FILTERS.length !== 100) console.warn("Expected 100 filters, got", FILTERS.length);
module.exports = { FILTERS, CATEGORIES };
